In [1]:
import pandas as pd

In [3]:
pd._version_

AttributeError: module 'pandas' has no attribute '_version_'

In [4]:
import pandas as pd

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [7]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [1]:
print(pd._version_)

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
print(pd._version_)

AttributeError: module 'pandas' has no attribute '_version_'

In [4]:
print(pd.__version__)

2.3.1


In [8]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

In [9]:
df.describe().round(2)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
count              9704.00        9222.00     8996.00         9704.00   
mean                199.71           3.96      149.66         3001.28   
std                  49.46           2.00       29.88          497.89   
min                  10.00           0.00       37.00          952.68   
25%                 170.00           3.00      130.00         2666.25   
50%                 200.00           4.00      149.00         2993.23   
75%                 230.00           5.00      170.00         3334.96   
max                 380.00          13.00      271.00         4739.08   

       acceleration  model_year  num_doors  fuel_efficiency_mpg  
count       8774.00     9704.00    9202.00              9704.00  
mean          15.02     2011.48      -0.01                14.99  
std            2.51        6.66       1.05                 2.56  
min            6.00     2000.00      -4.00                 6.20  
25%           13.30     2006.00      -1.00                13.27  
50%           15.00     2012.00       0.00                15.01  
75%           16.70     2017.00       1.00                16.71  
max           24.30     2023.00       4.00                25.97

In [10]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [11]:
df.fuel_type.nunique()

2

In [13]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [14]:
df.isnull()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   False          False       False           False   
1                   False          False       False           False   
2                   False           True       False           False   
3                   False          False        True           False   
4                   False          False       False           False   
...                   ...            ...         ...             ...   
9699                False          False       False           False   
9700                False           True       False           False   
9701                False          False       False           False   
9702                False          False       False           False   
9703                False          False       False           False   

      acceleration  model_year  origin  fuel_type  drivetrain  num_doors  \
0            False       False   False      False       False      False   
1            False       False   False      False       False      False   
2            False       False   False      False       False      False   
3            False       False   False      False       False      False   
4            False       False   False      False       False      False   
...            ...         ...     ...        ...         ...        ...   
9699         False       False   False      False       False       True   
9700         False       False   False      False       False      False   
9701         False       False   False      False       False      False   
9702         False       False   False      False       False      False   
9703         False       False   False      False       False      False   

      fuel_efficiency_mpg  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
9699                False  
9700                False  
9701                False  
9702                False  
9703                False  

[9704 rows x 11 columns]

In [3]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [10]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [11]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [13]:
asian_cars = df[df['origin'] == 'Asia']

In [14]:
asian_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [15]:
asian_cars.vehicle_weight.sum()

np.float64(9761430.865104277)

In [16]:
asian_cars.fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [17]:
df.horsepower.describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [20]:
df.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [21]:
most_frequent_hp = df.horsepower.mode()

In [22]:
print(most_frequent_hp)

0    152.0
Name: horsepower, dtype: float64


In [23]:
most_frequent_hp = df.horsepower.value_counts().idxmax()

In [24]:
most_frequent_hp

np.float64(152.0)

In [25]:
df_hp_filled = df.horsepower.fillna(152)
print(df_hp_filled)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64


In [26]:
df_hp_filled

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [27]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [28]:
df_hp_filled = df.fillna({'horsepower': 152})

In [29]:
df_hp_filled

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0       152.0     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [30]:
print(df.horsepower.median())
print(df_hp_filled.horsepower.median())

149.0
152.0


In [31]:
asian_cars

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0         NaN     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [33]:
asian_cars['vehicle_weight']

8       2714.219310
12      2783.868974
14      3582.687368
20      2231.808142
21      2659.431451
           ...     
9688    3948.404625
9692    3680.341381
9693    2545.070139
9698    3107.427820
9703    2908.043477
Name: vehicle_weight, Length: 3247, dtype: float64

In [36]:
asian_cars[['vehicle_weight','model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [39]:
x = asian_cars[['vehicle_weight','model_year']].head(n=7).to_numpy()

In [40]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [42]:
XTX = x.dot(x.T)

In [43]:
XTX

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [44]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [45]:
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [47]:
import nunmpy as np

ModuleNotFoundError: No module named 'nunmpy'

In [48]:
import numpy as np

In [49]:
np.linalg.inv(XTX)

array([[ 5.14065606e+08,  5.48536130e+07, -3.76831385e+08,
        -5.99044087e+08,  4.10105044e+08, -7.87026143e+07,
         7.23633092e+07],
       [ 3.29129898e+08,  8.26109025e+08, -3.72548813e+08,
        -7.01583859e+08,  3.27222378e+07, -5.67206124e+07,
        -5.80223502e+07],
       [-6.16516597e+08, -2.64221399e+08,  2.93298395e+08,
         7.94190283e+08, -1.94689452e+08, -1.53391689e+08,
         1.43457519e+08],
       [-4.98522990e+08, -2.71174593e+08,  5.34131775e+08,
         7.89486336e+08, -2.49261495e+08, -2.49261495e+08,
        -5.20318918e+07],
       [-0.00000000e+00, -2.68435456e+08,  2.23517418e-07,
         2.03703699e+08, -2.68435456e+08,  2.68435456e+08,
         6.46082210e+07],
       [ 0.00000000e+00, -1.15043767e+08, -1.15043767e+08,
        -2.70361224e+08,  2.68435456e+08,  2.68435456e+08,
        -3.76263766e+07],
       [ 2.68435456e+08,  3.83479223e+07,  3.83479223e+07,
        -2.12927011e+08,  0.00000000e+00,  0.00000000e+00,
        -1.3225025

In [50]:
w = (np.linalg.inv(XTX).dot(x.T)).dot(y)

ValueError: shapes (7,7) and (2,7) not aligned: 7 (dim 1) != 2 (dim 0)

In [55]:
np.linalg.inv(XTX).dot(x.T)

ValueError: shapes (7,7) and (2,7) not aligned: 7 (dim 1) != 2 (dim 0)

In [56]:
np.linalg.inv(XTX)

array([[ 5.14065606e+08,  5.48536130e+07, -3.76831385e+08,
        -5.99044087e+08,  4.10105044e+08, -7.87026143e+07,
         7.23633092e+07],
       [ 3.29129898e+08,  8.26109025e+08, -3.72548813e+08,
        -7.01583859e+08,  3.27222378e+07, -5.67206124e+07,
        -5.80223502e+07],
       [-6.16516597e+08, -2.64221399e+08,  2.93298395e+08,
         7.94190283e+08, -1.94689452e+08, -1.53391689e+08,
         1.43457519e+08],
       [-4.98522990e+08, -2.71174593e+08,  5.34131775e+08,
         7.89486336e+08, -2.49261495e+08, -2.49261495e+08,
        -5.20318918e+07],
       [-0.00000000e+00, -2.68435456e+08,  2.23517418e-07,
         2.03703699e+08, -2.68435456e+08,  2.68435456e+08,
         6.46082210e+07],
       [ 0.00000000e+00, -1.15043767e+08, -1.15043767e+08,
        -2.70361224e+08,  2.68435456e+08,  2.68435456e+08,
        -3.76263766e+07],
       [ 2.68435456e+08,  3.83479223e+07,  3.83479223e+07,
        -2.12927011e+08,  0.00000000e+00,  0.00000000e+00,
        -1.3225025

In [57]:
XTX_inv = np.linalg.inv(XTX)

In [58]:
XTX_inv.dot(x.T)

ValueError: shapes (7,7) and (2,7) not aligned: 7 (dim 1) != 2 (dim 0)

In [59]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [60]:
XT = x.T

In [61]:
XTX = XT.dot(x)

In [62]:
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [69]:
w = (np.linalg.inv(XTX).dot(x.T)).dot(y)

In [64]:
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [68]:
XTX_inv = np.linalg.inv(XTX)

In [70]:
w

array([0.01386421, 0.5049067 ])

In [71]:
w.sum()

np.float64(0.5187709081074016)